const sampleClasses = [
  {
    name: "Class 1A",
    year: "2024",
    teacher: "Mr. Smith",
    fees: "1500",
    students: ["Alice Johnson", "Bob Brown", "Charlie Davis"],
  },
  {
    name: "Class 1B",
    year: "2024",
    teacher: "Ms. Johnson",
    fees: "1500",
    students: ["David Evans", "Eva Green", "Frank Harris"],
  },
  {
    name: "Class 2A",
    year: "2023",
    teacher: "Mr. Taylor",
    fees: "1600",
    students: ["George Lewis", "Hannah Martin", "Ivy Nelson"],
  },
  {
    name: "Class 2B",
    year: "2023",
    teacher: "Ms. White",
    fees: "1600",
    students: ["Jack Owen", "Kathy Perry", "Liam Quinn"],
  },
  {
    name: "Class 3A",
    year: "2022",
    teacher: "Mr. Lee",
    fees: "1700",
    students: ["Mia Roberts", "Noah Scott", "Olivia Turner"],
  },
  {
    name: "Class 3B",
    year: "2022",
    teacher: "Ms. Hall",
    fees: "1700",
    students: ["Paul Wilson", "Quincy Young", "Rachel Adams"],
  },
  {
    name: "Class 4A",
    year: "2021",
    teacher: "Mr. King",
    fees: "1800",
    students: ["Sam Baker", "Tina Carter", "Uma Dawson"],
  },
  {
    name: "Class 4B",
    year: "2021",
    teacher: "Ms. Moore",
    fees: "1800",
    students: ["Victor Edwards", "Wendy Fisher", "Xander Graham"],
  },
  {
    name: "Class 5A",
    year: "2020",
    teacher: "Mr. Hernandez",
    fees: "1900",
    students: ["Yara Hill", "Zane James", "Anna Kelly"],
  },
  {
    name: "Class 5B",
    year: "2020",
    teacher: "Ms. Clark",
    fees: "1900",
    students: ["Ben Lewis", "Cara Miller", "Dylan Nash"],
  },
  {
    name: "Class 6A",
    year: "2019",
    teacher: "Mr. Rodriguez",
    fees: "2000",
    students: ["Ella Owens", "Finn Parker", "Grace Ramirez"],
  },
  {
    name: "Class 6B",
    year: "2019",
    teacher: "Ms. Martinez",
    fees: "2000",
    students: ["Henry Sanders", "Isla Thompson", "Jake Watson"],
  },
  {
    name: "Class 7A",
    year: "2018",
    teacher: "Mr. Walker",
    fees: "2100",
    students: ["Kara Young", "Leo Adams", "Mason Brown"],
  },
  {
    name: "Class 7B",
    year: "2018",
    teacher: "Ms. Lopez",
    fees: "2100",
    students: ["Nina Clark", "Owen Davis", "Piper Evans"],
  },
  {
    name: "Class 8A",
    year: "2017",
    teacher: "Mr. Hill",
    fees: "2200",
    students: ["Quinn Fisher", "Riley Garcia", "Sophie Hall"],
  },
];

export default sampleClasses;
